services:
  angular-app:
    build: .
    container_name: mb-website-angular
    working_dir: /app
    volumes:
      - .:/app
      - firebase-config:/root/.config
      - firebase-emulators:/root/.cache/firebase/emulators
    ports:
      - "4200:4200"   # Angular dev server
      - "4000:4000"   # Firebase Emulator UI
      - "8080:8080"   # Firestore
      - "9099:9099"   # Auth
      - "9199:9199"   # Storage
    command: >
      sh -c "npm install && rm -rf .angular/cache && npm run start -- --host 0.0.0.0 --poll 2000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  firebase-config:
  firebase-emulators:
